---
title: "Appendix 2"
author: "Jimmy Teague, Kanav Malik"
date: "December 3,2020"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 6
    theme: cerulean
    fig_caption: true
    number_sections: false
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(warn=-1)
```

**Libraries used**
```{r cars}
library(MASS)
library(klaR)
library(lattice)
library(ggplot2)
library(caret)
library(e1071)
library(cluster)
library(class)
library(dplyr)
library(factoextra)
library(ggplot2)
```


**Heart Data**
```{r pressure, echo=FALSE}

Heart_Data <- read.csv("heart.csv")
str(Heart_Data)  

## Convert categorical data to factor datatype
Heart_Data$sex <- as.factor(Heart_Data$sex)
Heart_Data$cp <- as.factor(Heart_Data$cp)
Heart_Data$fbs <- as.factor(Heart_Data$fbs)
Heart_Data$restecg <- as.factor(Heart_Data$restecg)
Heart_Data$exang <- as.factor(Heart_Data$exang)
Heart_Data$slope <- as.factor(Heart_Data$slope)
Heart_Data$ca <- as.factor(Heart_Data$ca)
Heart_Data$thal <- as.factor(Heart_Data$thal)
Heart_Data$target <- as.factor(Heart_Data$target)

str(Heart_Data)
```

**Create a function to perform K means clustering for K= 1 to 5, and get TWSS**
```{r,echo=TRUE}

set.seed(2700)
disheart_1 <- daisy(Heart_Data,metric="gower")
heartmat1 <- as.matrix(disheart_1)

km.out2 <- eclust(heartmat1,FUNcluster = "kmeans",k=2,nstart=50,nboot=50)
fviz_nbclust(heartmat1,FUNcluster = kmeans,method = "silhouette")
fviz_nbclust(heartmat1,FUNcluster = kmeans,method = "wss")

fviz_cluster(km.out2,geom="point",ellipse.type = "norm",palette="jco",ggtheme = theme_minimal())

```

**Validation set approach(Test/Train Split)**
```{r,echo=TRUE}
set.seed(2704)
roww <- nrow(Heart_Data)
coll <- ncol(Heart_Data)
numTrain <- floor(0.8 * roww) ##(Choose 80% data as training data)
numTest <- roww - numTrain
training <- Heart_Data[sample(roww, numTrain), ]
test <- Heart_Data[sample(roww, numTest), ]

```


**Standardize the interval predictors of training and test data for knn and svm, and create dummy variables for the categorical variables**
```{r,echo=TRUE}

## Store original train,test data in a new train,test data which will be modified for knn,svm
training_knn_svm <- training
test_knn_svm <- test 

## Standardize interval predictors of training,test data
training_knn_svm$誰..age <- scale(training_knn_svm$誰..age)
training_knn_svm$trestbps <- scale(training_knn_svm$trestbps)
training_knn_svm$chol <- scale(training_knn_svm$chol)
training_knn_svm$thalach <- scale(training_knn_svm$thalach)
training_knn_svm$oldpeak <- scale(training_knn_svm$oldpeak)
test_knn_svm$誰..age <- scale(test_knn_svm$誰..age)
test_knn_svm$trestbps <- scale(test_knn_svm$trestbps)
test_knn_svm$chol <- scale(test_knn_svm$chol)
test_knn_svm$thalach <- scale(test_knn_svm$thalach)
test_knn_svm$oldpeak <- scale(test_knn_svm$oldpeak)

## Create dummies for the categorical predictors
dummies_train <- dummyVars(~ ., data=training_knn_svm[,-c(1,4,5,8,10,14)])
c2_train <- predict(dummies_train, training_knn_svm[,-14])

dummies_test <- dummyVars(~ ., data=test_knn_svm[,-c(1,4,5,8,10,14)])
c2_test <- predict(dummies_test, test_knn_svm[,-14])

#Combine dummy and normalized data along with the target variable for train and test set
dum_norm_train <- as.data.frame(cbind(training_knn_svm[,c(14,1,4,5,8,10)], c2_train))
dum_norm_test <- as.data.frame(cbind(test_knn_svm[,c(14,1,4,5,8,10)], c2_test))

```


**KNN**

```{r,echo=TRUE}

train.Predictors <- data.frame(dum_norm_train[,c(-1)]) ## training predictors
train.Response <- dum_norm_train[,"target"] ## training response variable
test.Predictors <- data.frame(dum_norm_test[,c(-1)]) ## testing predictors
test.Response <- dum_norm_test[,"target"] ## testing response variable

knn.best <- tune.knn(train.Predictors,train.Response,k=seq(2,50,by=1))
knn.best

knn.pred_train <- knn(train.Predictors,train.Predictors,train.Response,k=knn.best$best.parameters[,1])
knn.pred_test <- knn(train.Predictors,test.Predictors,train.Response,k=knn.best$best.parameters[,1])
confusionMatrix(knn.pred_train,as.factor(dum_norm_train$target))
paste("Train Accuracy Rate =",round(1 - mean(knn.pred_train != dum_norm_train$target),4)*100,"%")
confusionMatrix(knn.pred_test,as.factor(dum_norm_test$target))
paste("Test Accuracy Rate =",round(1 - mean(knn.pred_test != dum_norm_test$target),4)*100,"%")

```

**SVM**
```{r,echo=TRUE,warning=FALSE}
set.seed(403)

## Linear kernel
tune.out.linear <- tune.svm(target ~., data=dum_norm_train, kernel='linear', cost=seq(0.1,15,by=0.25), 
                            gamma = seq(0.05,10,by=0.85))
summary(tune.out.linear$best.model)

svm_predict_train <- predict(tune.out.linear$best.model, dum_norm_train[,-1])
svm_predict_test <- predict(tune.out.linear$best.model, dum_norm_test[,-1])

confusionMatrix(svm_predict_train, dum_norm_train$target)
paste("Train accuracy rate for linear kernel =" ,
      round(1-mean(svm_predict_train != dum_norm_train[,"target"]),4)*100,"%")
confusionMatrix(svm_predict_test, dum_norm_test$target)
paste("Test accuracy rate for linear kernel =" ,
      round(1-mean(svm_predict_test != dum_norm_test[,"target"]),4)*100,"%")

#Polynomial kernel
tune.out.poly <- tune.svm(target ~., data=dum_norm_train, 
                     kernel='polynomial', cost=seq(0.1,15,by=0.25), gamma = seq(0.05,10,by=0.85),
                     degree=seq(1,10,by = 1))
summary(tune.out.poly$best.model)

svm_predict_train <- predict(tune.out.poly$best.model, dum_norm_train[,-1])
svm_predict_test <- predict(tune.out.poly$best.model, dum_norm_test[,-1])
confusionMatrix(svm_predict_train, dum_norm_train$target)
paste("Train accuracy rate for polynomial kernel =" ,
      round(1-mean(svm_predict_train != dum_norm_train[,"target"]),4)*100,"%")
confusionMatrix(svm_predict_test, dum_norm_test$target)
paste("Test accuracy rate for polynomial kernel =" ,
      round(1-mean(svm_predict_test != dum_norm_test[,"target"]),4)*100,"%")

## Radial kernel
tune.out.radial <- tune.svm(target ~., data=dum_norm_train, 
                 kernel='radial', cost=seq(0.1,15,by=0.25), gamma = seq(0.05,10,by=0.85))
summary(tune.out.radial$best.model)

svm_predict_train <- predict(tune.out.radial$best.model, dum_norm_train[,-1])
svm_predict_test <- predict(tune.out.radial$best.model, dum_norm_test[,-1])
confusionMatrix(svm_predict_train, dum_norm_train$target)
paste("Train accuracy rate for radial kernel =" ,
      round(1-mean(svm_predict_train != dum_norm_train[,"target"]),4)*100,"%")
confusionMatrix(svm_predict_test, dum_norm_test$target)
paste("Test accuracy rate for radial kernel =" ,
      round(1-mean(svm_predict_test != dum_norm_test[,"target"]),4)*100,"%")

```


**Naive Bayes**
```{r,echo=TRUE,warning=FALSE}

### KDC ###
nb1 <- NaiveBayes(target ~.,data=training, usekernel=T) 

pred_train <- predict(nb1, training[,1:13])
pred_test <- predict(nb1, test[,1:13])

confusionMatrix(pred_train$class,training$target)
paste("Train Accuracy Rate =",round(1 - mean(pred_train$class != training$target),4)*100,"%")
confusionMatrix(pred_test$class,test$target)
paste("Test Accuracy Rate =",round(1 - mean(pred_test$class != test$target),4)*100,"%")

```



```{r, Turning warnings on again,echo=FALSE}
options(warn=0)
```








